services:
  db:
    image: mysql:latest
    container_name: local-mysql-fastcampus
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=fastcampus
      - MYSQL_ROOT_HOST=%
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
